[Interface]
PrivateKey = +BMecIn0XRZ+q3CpLff/XeCehZKqs6I27B+5Dkbm7E0=
Address = 10.0.0.6/24
DNS = 8.8.8.8

[Peer]
PublicKey = 3LaurKRQr86dvQUg4PcEDQXim3ZXm4KJSLXHggLsZgI=
Endpoint = 54.207.77.13:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25